/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class TTT extends javax.swing.JFrame {

    /**
     * Creates new form TTT
     */
    public TTT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGameName = new javax.swing.JLabel();
        lblPlayerSymbol = new javax.swing.JLabel();
        pnlBoard = new javax.swing.JPanel();
        btn00 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        lblPlayerTurn = new javax.swing.JLabel();
        lblP1Score = new javax.swing.JLabel();
        lblP2Score = new javax.swing.JLabel();
        btnReload = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TIC TAC TOE GAME");
        setFont(new java.awt.Font("Cambria", 2, 48)); // NOI18N
        setResizable(false);

        lblGameName.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        lblGameName.setText("TIC TAC TOE GAME");
        lblGameName.setAlignmentX(1.0F);
        lblGameName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BOTTOM));

        lblPlayerSymbol.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        lblPlayerSymbol.setText("P1 SYMBOL: O and P2 SYMBOL: X");

        pnlBoard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlBoard.setLayout(new java.awt.GridLayout(3, 3));

        btn00.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });
        pnlBoard.add(btn00);

        btn01.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });
        pnlBoard.add(btn01);

        btn02.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });
        pnlBoard.add(btn02);

        btn10.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        pnlBoard.add(btn10);

        btn11.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        pnlBoard.add(btn11);

        btn12.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        pnlBoard.add(btn12);

        btn20.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        pnlBoard.add(btn20);

        btn21.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });
        pnlBoard.add(btn21);

        btn22.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });
        pnlBoard.add(btn22);

        lblPlayerTurn.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblPlayerTurn.setText("Player Turn");

        lblP1Score.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        lblP1Score.setText("P1 SCORE: 0");

        lblP2Score.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        lblP2Score.setText("P2 SCORE: 0");

        btnReload.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        btnReload.setText("Reload");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnReturn.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(lblPlayerSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(pnlBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReload)
                                .addGap(13, 13, 13)
                                .addComponent(btnReturn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPlayerTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblP1Score, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                            .addComponent(lblP2Score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lblGameName, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblGameName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayerSymbol)
                    .addComponent(lblPlayerTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pnlBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblP1Score)
                        .addGap(30, 30, 30)
                        .addComponent(lblP2Score)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReload)
                            .addComponent(btnReset)
                            .addComponent(btnReturn))))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        turn=0;
        P1Score=0;
        P2Score=0;
        unlockBoard();
        lblPlayerTurn.setText("PLAYER TURN " + (turn+1));
        lblP1Score.setText("P1 SCORE : 0");
        lblP2Score.setText("P2 SCORE : 0");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        // TODO add your handling code here:
        unlockBoard();
        turn=0;
        lblPlayerTurn.setText("PLAYER TURN " + (turn+1));
    }//GEN-LAST:event_btnReloadActionPerformed

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
        // TODO add your handling code here:
        if(turn%2==0)
        {
            btn00.setEnabled(false);
            btn00.setText("O");
            board[0][0]='O';
            if(checkWinner('O')){
                lockBoard();
                P1Score++;
                lblP1Score.setText("Player 1 Score:"+P1Score);
            }
            turn++;
            lblPlayerTurn.setText("Player Turn :" + ((turn%2)+1));
        }
        else{
            btn00.setEnabled(false);
            btn00.setText("X");
            board[0][0]='X';
            if(checkWinner('X')){
                lockBoard();
                P2Score++;
                lblP2Score.setText("Player 2 Score:"+P2Score);
            }
            turn++;
            lblPlayerTurn.setText("Player Turn :" + ((turn%2)+1));  
        }
    }//GEN-LAST:event_btn00ActionPerformed

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        // TODO add your handling code here:
          if(turn%2==0)
        {
            btn01.setEnabled(false);
            btn01.setText("O");
            board[0][1]='O';
            if(checkWinner('O')){
                lockBoard();
                P1Score++;
                lblP1Score.setText("Player 1 Score:"+P1Score);
            }
            turn++;
            lblPlayerTurn.setText("Player Turn :" + ((turn%2)+1));
        }
        else{
            btn01.setEnabled(false);
            btn01.setText("X");
            board[0][1]='X';
            if(checkWinner('X')){
                lockBoard();
                P2Score++;
                lblP2Score.setText("Player 2 Score:"+P2Score);
            }
            turn++;
            lblPlayerTurn.setText("Player Turn :" + ((turn%2)+1));  
        }
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        // TODO add your handling code here:
          if(turn%2==0)
        {
            btn02.setEnabled(false);
            btn02.setText("O");
            board[0][2]='O';
            if(checkWinner('O')){
                lockBoard();
                P1Score++;
                lblP1Score.setText("Player 1 Score:"+P1Score);
            }
            turn++;
            lblPlayerTurn.setText("Player Turn :" + ((turn%2)+1));
        }
        else{
            btn02.setEnabled(false);
            btn02.setText("X");
            board[0][2]='X';
            if(checkWinner('X')){
                lockBoard();
                P2Score++;
                lblP2Score.setText("Player 2 Score:"+P2Score);
            }
            turn++;
            lblPlayerTurn.setText("Player Turn :" + ((turn%2)+1));  
        }
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
          if(turn%2==0)
        {
            btn10.setEnabled(false);
            btn10.setText("O");
            board[1][0]='O';
            if(checkWinner('O')){
                lockBoard();
                P1Score++;
                lblP1Score.setText("Player 1 Score:"+P1Score);
            }
            turn++;
            lblPlayerTurn.setText("Player Turn :" + ((turn%2)+1));
        }
        else{
            btn10.setEnabled(false);
            btn10.setText("X");
            board[1][0]='X';
            if(checkWinner('X')){
                lockBoard();
                P2Score++;
                lblP2Score.setText("Player 2 Score:"+P2Score);
            }
            turn++;
            lblPlayerTurn.setText("Player Turn :" + ((turn%2)+1));  
        }
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        // TODO add your handling code here:
          if(turn%2==0)
        {
            btn11.setEnabled(false);
            btn11.setText("O");
            board[1][1]='O';
            if(checkWinner('O')){
                lockBoard();
                P1Score++;
                lblP1Score.setText("Player 1 Score:"+P1Score);
            }
            turn++;
            lblPlayerTurn.setText("Player Turn :" + ((turn%2)+1));
        }
        else{
            btn11.setEnabled(false);
            btn11.setText("X");
            board[1][1]='X';
            if(checkWinner('X')){
                lockBoard();
                P2Score++;
                lblP2Score.setText("Player 2 Score:"+P2Score);
            }
            turn++;
            lblPlayerTurn.setText("Player Turn :" + ((turn%2)+1));  
        }
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        // TODO add your handling code here:
          if(turn%2==0)
        {
            btn12.setEnabled(false);
            btn12.setText("O");
            board[1][2]='O';
            if(checkWinner('O')){
                lockBoard();
                P1Score++;
                lblP1Score.setText("Player 1 Score:"+P1Score);
            }
            turn++;
            lblPlayerTurn.setText("Player Turn :" + ((turn%2)+1));
        }
        else{
            btn12.setEnabled(false);
            btn12.setText("X");
            board[1][2]='X';
            if(checkWinner('X')){
                lockBoard();
                P2Score++;
                lblP2Score.setText("Player 2 Score:"+P2Score);
            }
            turn++;
            lblPlayerTurn.setText("Player Turn :" + ((turn%2)+1));  
        }
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        // TODO add your handling code here:
          if(turn%2==0)
        {
            btn20.setEnabled(false);
            btn20.setText("O");
            board[2][0]='O';
            if(checkWinner('O')){
                lockBoard();
                P1Score++;
                lblP1Score.setText("Player 1 Score:"+P1Score);
            }
            turn++;
            lblPlayerTurn.setText("Player Turn :" + ((turn%2)+1));
        }
        else{
            btn20.setEnabled(false);
            btn20.setText("X");
            board[2][0]='X';
            if(checkWinner('X')){
                lockBoard();
                P2Score++;
                lblP2Score.setText("Player 2 Score:"+P2Score);
            }
            turn++;
            lblPlayerTurn.setText("Player Turn :" + ((turn%2)+1));  
        }
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        // TODO add your handling code here:
          if(turn%2==0)
        {
            btn21.setEnabled(false);
            btn21.setText("O");
            board[2][1]='O';
            if(checkWinner('O')){
                lockBoard();
                P1Score++;
                lblP1Score.setText("Player 1 Score:"+P1Score);
            }
            turn++;
            lblPlayerTurn.setText("Player Turn :" + ((turn%2)+1));
        }
        else{
            btn21.setEnabled(false);
            btn21.setText("X");
            board[2][1]='X';
            if(checkWinner('X')){
                lockBoard();
                P2Score++;
                lblP2Score.setText("Player 2 Score:"+P2Score);
            }
            turn++;
            lblPlayerTurn.setText("Player Turn :" + ((turn%2)+1));  
        }
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        // TODO add your handling code here:
          if(turn%2==0)
        {
            btn22.setEnabled(false);
            btn22.setText("O");
            board[2][2]='O';
            if(checkWinner('O')){
                lockBoard();
                P1Score++;
                lblP1Score.setText("Player 1 Score:"+P1Score);
            }
            turn++;
            lblPlayerTurn.setText("Player Turn :" + ((turn%2)+1));
        }
        else{
            btn22.setEnabled(false);
            btn22.setText("X");
            board[2][2]='X';
            if(checkWinner('X')){
                lockBoard();
                P2Score++;
                lblP2Score.setText("Player 2 Score:"+P2Score);
            }
            turn++;
            lblPlayerTurn.setText("Player Turn :" + ((turn%2)+1));  
        }
    }//GEN-LAST:event_btn22ActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        int i= JOptionPane.showConfirmDialog(TTT.this, "You Want To Return", "Return", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if(i==0){
                   new Start().setVisible(true);
                   this.dispose();
                }
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TTT().setVisible(true);
            }
        });
    }
   void lockBoard(){
       for(int i=0;i<9;i++)
           pnlBoard.getComponent(i).setEnabled(false);
   }
   void unlockBoard(){
       for(int i=0;i<9;i++)
           pnlBoard.getComponent(i).setEnabled(true);
       btn00.setText("");
       btn01.setText("");
       btn02.setText("");
       btn10.setText("");
       btn11.setText("");
       btn12.setText("");
       btn20.setText("");
       btn21.setText("");
       btn22.setText("");
       turn=0;
       for(int i=0;i<3;i++)
          for(int j=0;j<3;j++)
              board[i][j]=' ';
   }
   
   boolean checkWinner(char Symbol){
       for(int i=0;i<3;i++){
           if( (board[i][0]==Symbol) && (board[i][1]==Symbol) && (board[i][2]==Symbol)){
               //Row Winner Check
               return true;
           }
           if( (board[0][i]==Symbol) && (board[1][i]==Symbol) && (board[2][i]==Symbol)){
               //Column Winner Check
               return true;
           }
       }
           if( (board[0][0]==Symbol) && (board[1][1]==Symbol) && (board[2][2]==Symbol)){
               //Top Left Diagional Check
               return true;
           }
           if( (board[0][2]==Symbol) && (board[1][1]==Symbol) && (board[2][0]==Symbol)){
               //Top Right Diagonal Winner Check
               return true;
           }
               return false;
   }
    char [][] board = new char[3][3];
    int turn = 0;
    int P1Score = 0;
    int P2Score = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel lblGameName;
    private javax.swing.JLabel lblP1Score;
    private javax.swing.JLabel lblP2Score;
    private javax.swing.JLabel lblPlayerSymbol;
    private javax.swing.JLabel lblPlayerTurn;
    private javax.swing.JPanel pnlBoard;
    // End of variables declaration//GEN-END:variables
    }
